Tensors

In TensorFlow, data is represented as multi-dimensional arrays or matrices called tensors. Tensors are the core building blocks of TensorFlow.

In [ ]:
import tensorflow as tf

# Create a constant tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print(tensor)

Output

tf.Tensor(

[[1 2 3]

 [4 5 6]],
 shape=(2, 3)

Variables

A Variable in TensorFlow is a tensor whose value can be changed during execution. They are typically used for storing parameters (e.g., weights and biases) in machine learning models.

In [ ]:
var = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

print(var)
Output:

#<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
#array([[1., 2.],
#       [3., 4.]], dtype=float32)>

 Operations

TensorFlow allows you to perform a variety of operations on tensors, such as addition, multiplication, matrix multiplication, etc.

In [ ]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
result = tf.matmul(a, b)

print(result)
#Output:

#tf.Tensor(
#[[19 22]
# [43 50]], shape=(2, 2), dtype=int32)

Gradient Descent and Auto-Differentiation

In machine learning, gradient descent is used to minimize the loss function. TensorFlow’s tf.GradientTape() automatically computes gradients for you.

he line with tf.GradientTape() as tape: in TensorFlow creates a context manager called tape that records operations performed within its scope

In [ ]:
# Example function: y = x^2
x = tf.Variable(3.0)

# Use GradientTape to compute the gradient of y = x^2 with respect to x
with tf.GradientTape() as tape:
    y = x**2

# Compute the gradient of y with respect to x
grad = tape.gradient(y, x)

print(grad)  # Output: 6.0

Neural Network Layers (Keras API)

TensorFlow includes tf.keras, which is a high-level API for building neural networks. You can define neural networks using layers, compile the model, and train i

In [ ]:
from tensorflow.keras import layers, models

# Create a simple Sequential model
model = models.Sequential()

# Add layers
model.add(layers.Dense(128, activation='relu', input_shape=(784,)))
model.add(layers.Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print model summary
model.summary()

 Training a Model

TensorFlow provides built-in functions to fit your model on training data and evaluate it on test data.

In [ ]:
# Dummy data
import numpy as np
X_train = np.random.rand(100, 784)
y_train = np.random.randint(0, 10, 100)

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=32)

Saving and Loading Models

You can save a trained model in TensorFlow and load it later for inference.

Example (Saving a model):

# Save the model


In [ ]:
model.save('my_model.h5')
Example (Loading a model):

# Load the model



In [ ]:
new_model = tf.keras.models.load_model('my_model.h5')


# Use the model for inference


In [ ]:
predictions = new_model.predict(X_train)

Dataset API

The tf.data API is a powerful utility for loading and processing large datasets efficiently. It can handle everything from reading data from disk to performing transformations such as shuffling and batching.

# Create a dataset from a numpy array



In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))


# Shuffle and batch the dataset


In [ ]:
dataset = dataset.shuffle(buffer_size=1024).batch(32)



# Iterate through the dataset


In [ ]:
for batch in dataset:
    print(batch)

Custom Training Loops

For more complex models, TensorFlow allows you to write custom training loops using tf.GradientTape() for more fine-grained control over the training process.


In [ ]:
# A simple custom training loop
epochs = 3
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        predictions = model(X_train)
        loss = tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(y_train, predictions))

    # Compute gradients
    gradients = tape.gradient(loss, model.trainable_variables)

    # Update model weights
    optimizer = tf.keras.optimizers.Adam()
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    print(f'Epoch {epoch+1}, Loss: {loss.numpy()}')


Distributed Training

TensorFlow provides support for distributed training, allowing you to train models on multiple devices (like GPUs or TPUs) with ease.



In [ ]:
# Create a mirrored strategy for distributed training
strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    # Build and compile the model inside the strategy's scope
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(784,)))
    model.add(layers.Dense(10, activation='softmax'))

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5)